### ISSUE TITLE
Chat error

### ISSUE THREAD

**Issue by svivian** [svivian/Pokemon-Showdown#148]
Here is the error on the server from the latest update:

    CRASH: TypeError: Cannot read property 'lobby' of undefined
        at canTalk (/var/www/showdown/app/command-parser.js:579:29)
        at Object.exports.parse (/var/www/showdown/app/command-parser.js:514:12)
        at Room.chat (/var/www/showdown/app/rooms.js:86:27)
        at User.chat (/var/www/showdown/app/users.js:1609:9)
        at Function.Users.socketReceive (/var/www/showdown/app/users.js:373:12)
        at Worker.<anonymous> (/var/www/showdown/app/sockets.js:45:11)
        at Worker.emit (events.js:98:17)
        at ChildProcess.emit (events.js:98:17)
        at handleMessage (child_process.js:322:10)
        at Pipe.channel.onread (child_process.js:349:11)

    CRASH: TypeError: Cannot read property 'lobby' of undefined
        at canTalk (/var/www/showdown/app/command-parser.js:579:29)
        at Object.exports.parse (/var/www/showdown/app/command-parser.js:514:12)
        at Room.chat (/var/www/showdown/app/rooms.js:86:27)
        at User.processChatQueue (/var/www/showdown/app/users.js:1625:13)
        at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)

**Comment by Scizornician** [comment]
I just made an edit, hopefully that should fix it.

**Comment by svivian** [comment]
Seems to have done the trick.
